# Generated by Django 3.2.12 on 2022-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_pates_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boisson',
            name='allergene',
            field=models.ManyToManyField(to='menu.Allergene'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='allergene',
            field=models.ManyToManyField(to='menu.Allergene'),
        ),
        migrations.AddField(
            model_name='entree',
            name='allergene',
            field=models.ManyToManyField(to='menu.Allergene'),
        ),
        migrations.AddField(
            model_name='pates',
            name='allergene',
            field=models.ManyToManyField(to='menu.Allergene'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='allergene',
            field=models.ManyToManyField(to='menu.Allergene'),
        ),
    ]
