# Generated by Django 3.2.12 on 2022-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20220222_1413'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pizza',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='allergene',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_allergene_name'),
        ),
        migrations.AddConstraint(
            model_name='boisson',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_boisson_name'),
        ),
        migrations.AddConstraint(
            model_name='dessert',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_dessert_name'),
        ),
        migrations.AddConstraint(
            model_name='entree',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_entree_name'),
        ),
        migrations.AddConstraint(
            model_name='pates',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_pates_name'),
        ),
        migrations.AddConstraint(
            model_name='pizza',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_pizza_name'),
        ),
    ]
