# Generated by Django 3.2.12 on 2022-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20220222_1417'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('nom',), name='unique_ingredient_name'),
        ),
    ]
