# Generated by Django 3.2.12 on 2022-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_ingredient_unique_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boisson',
            name='allergene',
            field=models.ManyToManyField(blank=True, to='menu.Allergene'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='allergene',
            field=models.ManyToManyField(blank=True, to='menu.Allergene'),
        ),
        migrations.AlterField(
            model_name='entree',
            name='allergene',
            field=models.ManyToManyField(blank=True, to='menu.Allergene'),
        ),
        migrations.AlterField(
            model_name='pates',
            name='allergene',
            field=models.ManyToManyField(blank=True, to='menu.Allergene'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='allergene',
            field=models.ManyToManyField(blank=True, to='menu.Allergene'),
        ),
    ]
