# Generated by Django 3.2.12 on 2022-03-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20220321_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pates',
            options={'verbose_name_plural': 'Pates'},
        ),
    ]
