# Generated by Django 3.2.12 on 2022-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to=''),
        ),
    ]
