# Generated by Django 3.2.12 on 2022-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=''),
        ),
    ]
