# Generated by Django 3.2.12 on 2022-05-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20220530_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image_width',
        ),
    ]
