# Generated by Django 3.2.12 on 2022-05-30 11:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20220530_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[500, 300], upload_to=''),
        ),
    ]
