# Generated by Django 3.2.12 on 2022-06-06 08:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boisson',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[750, 650], upload_to=''),
        ),
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[750, 650], upload_to=''),
        ),
        migrations.AddField(
            model_name='entree',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[750, 650], upload_to=''),
        ),
        migrations.AddField(
            model_name='pates',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[750, 650], upload_to=''),
        ),
    ]
