# Generated by Django 3.2.12 on 2023-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_auto_20230331_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='annonce',
            field=models.TextField(null=True),
        ),
    ]
