# Generated by Django 3.2.12 on 2023-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_alter_annonce_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='annonce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
