# Generated by Django 3.2.12 on 2023-04-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_annonce_annonce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': '1. Pizzas'},
        ),
    ]
